version: '3.8'

services:
  postgres:
    container_name: feed_back_sistem
    image: postgres
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=local_user
    - POSTGRES_PASSWORD=local_password
    - POSTGRES_DB=feed_back
